# Generated by Django 4.2 on 2023-05-02 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Denumirea')),
                ('address', models.CharField(max_length=150, verbose_name='Adresa')),
                ('district', models.CharField(max_length=74, verbose_name='Raionul')),
                ('village', models.CharField(max_length=55, verbose_name='Satul')),
                ('street', models.CharField(max_length=155, verbose_name='Strada')),
                ('code_cuiio', models.IntegerField()),
                ('code_idno', models.IntegerField()),
                ('ruler', models.CharField(max_length=150, verbose_name='Conducătorul')),
                ('accountant', models.CharField(max_length=150, verbose_name='Contabil')),
                ('executor', models.CharField(max_length=150, verbose_name='Executantul')),
                ('tel', models.CharField(max_length=15, verbose_name='Tel')),
                ('anul', models.CharField(max_length=5, verbose_name='Anul')),
            ],
        ),
        migrations.CreateModel(
            name='InfEconOp',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('n_year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('n_month', models.IntegerField(blank=True, null=True, verbose_name='Month')),
                ('n_beforeTotal', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('n_beforeLunar', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('n_total', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('n_lunar', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Company')),
            ],
            options={
                'unique_together': {('code', 'counter')},
            },
        ),
    ]
