# Generated by Django 4.1.5 on 2023-06-13 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestitiiActive1',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('codul_rind', models.IntegerField(blank=True, null=True, verbose_name='Codul_rînd')),
                ('indicatori', models.CharField(blank=True, max_length=120, null=True, verbose_name='Indicatorii')),
                ('intrari', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('investitii', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_company_investitii', to='reports.companydata', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='InvestitiiActive2',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('codul_rind', models.IntegerField(blank=True, null=True, verbose_name='Codul_rînd')),
                ('indicatori', models.CharField(blank=True, max_length=120, null=True, verbose_name='Indicatorii')),
                ('code_cuatm', models.IntegerField(blank=True, null=True, verbose_name='CodCUATM')),
                ('numa_oras', models.CharField(blank=True, max_length=120, null=True, verbose_name='Numa_oras')),
                ('cladiri', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('apart', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('sup_total', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_company_investitii_2', to='reports.companydata', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerRaportStatisticTrimestrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.investitiiactive1', verbose_name='Investiţii în active imobilizate')),
                ('reports_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.investitiiactive2', verbose_name='Clădiri rezidenţiale (de locuit)')),
            ],
        ),
    ]
