# Generated by Django 4.1.5 on 2023-06-26 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balanta1',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('indicatorii', models.CharField(blank=True, max_length=520, null=True, verbose_name='Indicatorii')),
                ('code_rind', models.IntegerField(blank=True, null=True, verbose_name='cod_rind')),
                ('inceputul', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Începutul')),
                ('sfirsitul', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Sfîrșitul')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_company_balanta_1', to='reports.companydata', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Balanta2',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('indicatorii', models.CharField(blank=True, max_length=520, null=True, verbose_name='Indicatorii')),
                ('code_rind', models.IntegerField(blank=True, null=True, verbose_name='cod_rind')),
                ('precedenta', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='precedenta')),
                ('curenta', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='curenta')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_company_balanta_2', to='reports.companydata', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Balanta3',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('indicatorii', models.CharField(blank=True, max_length=520, null=True, verbose_name='Indicatorii')),
                ('code_rind', models.IntegerField(blank=True, null=True, verbose_name='cod_rind')),
                ('inceputul', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='începutul')),
                ('majorari', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Majorări')),
                ('diminuari', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Diminuări')),
                ('sfirsitul', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Sfîrşitul')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_company_balanta_3', to='reports.companydata', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerRaportBalanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.balanta1', verbose_name='BILANŢUL')),
                ('reports_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.balanta2', verbose_name='SITUAŢIA DE PROFIT ŞI PIERDERE')),
                ('reports_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.balanta3', verbose_name='SITUAŢIA MODIFICĂRILOR CAPITALULUI PROPRIU')),
                ('reports_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.stocuri2', verbose_name='SITUAŢIA FLUXURILOR DE NUMERAR')),
            ],
        ),
        migrations.CreateModel(
            name='Balanta4',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='Code')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('indicatorii', models.CharField(blank=True, max_length=520, null=True, verbose_name='Indicatorii')),
                ('code_rind', models.IntegerField(blank=True, null=True, verbose_name='cod_rind')),
                ('precedenta', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='precedentă')),
                ('curenta', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='curentă')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_company_balanta_4', to='reports.companydata', verbose_name='Company')),
            ],
        ),
    ]
