# Generated by Django 4.1.5 on 2023-06-01 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportitems3_reportitems2_reportitems1_reportheader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondinfeconop',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='reports.companydata', verbose_name='Company'),
        ),
        migrations.CreateModel(
            name='ManagerInfEconOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.infeconop', verbose_name='Первый отчет')),
            ],
        ),
    ]
