# Generated by Django 4.1.5 on 2023-06-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_balanta1_balanta2_balanta3_managerraportbalanta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerraportbalanta',
            name='reports_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.balanta4', verbose_name='SITUAŢIA FLUXURILOR DE NUMERAR'),
        ),
    ]
