# Generated by Django 4.1.5 on 2023-06-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_investitiiactive1_investitiiactive2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerraportstatistictrimestrial',
            name='reports_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.investitiiactive2', verbose_name='Clădiri rezidenţiale (de locuit)'),
        ),
    ]
