# Generated by Django 4.1.5 on 2023-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_secondinfeconop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondinfeconop',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Denumirea'),
        ),
    ]
