# Generated by Django 4.1.5 on 2023-05-12 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_secondinfeconop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='infeconop',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='secondinfeconop',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
