# Generated by Django 4.1.5 on 2023-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_managerraportbalanta_reports_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanta1',
            name='la',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='la'),
        ),
        migrations.AddField(
            model_name='balanta2',
            name='de_la',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='de_la'),
        ),
        migrations.AddField(
            model_name='balanta2',
            name='pina_la',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='de_la'),
        ),
        migrations.AddField(
            model_name='balanta3',
            name='de_la',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='de_la'),
        ),
        migrations.AddField(
            model_name='balanta3',
            name='pina_la',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='de_la'),
        ),
        migrations.AddField(
            model_name='balanta4',
            name='de_la',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='de_la'),
        ),
        migrations.AddField(
            model_name='balanta4',
            name='pina_la',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='de_la'),
        ),
    ]
