# Generated by Django 4.1.5 on 2023-05-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_infeconop_uid_secondinfeconop_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='infeconop',
            name='before_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Before Month'),
        ),
        migrations.AddField(
            model_name='infeconop',
            name='before_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Before Year'),
        ),
        migrations.AddField(
            model_name='secondinfeconop',
            name='before_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Before Month'),
        ),
        migrations.AddField(
            model_name='secondinfeconop',
            name='before_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Before Year'),
        ),
    ]
