# Generated by Django 4.1.5 on 2023-07-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_balanta1_la_balanta2_de_la_balanta2_pina_la_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanta1',
            name='la',
            field=models.DateField(null=True, verbose_name=''),
        ),
    ]
