# Generated by Django 4.1.5 on 2023-06-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_stocuri2_stocuri1_managerraportstocuri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerraportstocuri',
            old_name='ci_1',
            new_name='reports',
        ),
    ]
