# Generated by Django 4.1.5 on 2023-06-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_rename_ci_1_managerraportstocuri_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocuri2',
            name='trimestrul',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Trimestrul'),
        ),
    ]
