# Generated by Django 4.1.5 on 2023-06-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_managerinfeconop_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerinfeconop',
            name='reports_second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.secondinfeconop', verbose_name='Вторая часть'),
        ),
    ]
