# Generated by Django 4.1.5 on 2023-06-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_managerreportdescriereaasociati'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportheader',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Counter'),
        ),
        migrations.AddField(
            model_name='reportitems1',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Counter'),
        ),
        migrations.AddField(
            model_name='reportitems2',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Counter'),
        ),
        migrations.AddField(
            model_name='reportitems3',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Counter'),
        ),
    ]
