# Generated by Django 4.1.5 on 2023-06-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_reportheader_counter_reportitems1_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportheader',
            name='associat',
            field=models.BooleanField(null=True, verbose_name='Associat'),
        ),
        migrations.AlterField(
            model_name='reportheader',
            name='fondul',
            field=models.BooleanField(null=True, verbose_name='Fondul'),
        ),
        migrations.AlterField(
            model_name='reportitems3',
            name='perc',
            field=models.IntegerField(null=True, verbose_name='Perc'),
        ),
    ]
